#![allow(non_snake_case)]
use constcat::concat_slices;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Blocks {
    // Demo
    Air,
    Dirt,
    Stone,
    Cobblestone,
    WoodPlanks,
    Sand,
    Sandstone,
    Wool,
    Glass,
    BlockOfIron,
    BlockOfGold,
    BlockOfDiamond,
    Obsidian,
    Bricks,
    OakWood,
    StoneSlab,
    Ladder,
    Torch,
    Dandelion,
    Rose,
    BrownMushroom,
    RedMushroom,
    SugarCane,
    GrassBlock,
    OakLeaves,
    BirchLeaves,
    SpruceLeaves,
    BirchWood,
    SpruceWood,
    TNT,
    Snow,
    Water,

    // 0.1.0 alpha
    OakStairs,
    CobblestoneStairs,
    CoalOre,
    IronOre,
    DiamondOre,
    RedstoneOre,
    LapisLazuliOre,
    Ice,
    Gravel,
    Clay,
    Lava,
    Farmland,
    OakDoor,
    IronDoor,
    WoodSlab,
    CobblestoneSlab,
    SandstoneSlab,
    InvisibleBedrock,
    // 0.1.3 alpha
    InfoUpdate,
    InfoUpdate2,
    Cactus,
    // 0.2.0 alpha
    Fence,
    FenceGate,
    // White Wool
    SnowBlock,
    BookShelf,
    LapisLazuliBlock,
    MossyCobblestone,
    Reserved6,
    // 0.3.0 alpha
    CraftingTable,
    BrickSlab,
    BrickStair,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Items {
    // Demo
    Air,
    Dirt,
    Stone,
    Cobblestone,
    WoodPlanks,
    Sand,
    Sandstone,
    Wool,
    Glass,
    BlockOfIron,
    BlockOfGold,
    BlockOfDiamond,
    Obsidian,
    Bricks,
    OakWood,
    StoneSlab,
    Ladder,
    Torch,
    Dandelion,
    Rose,
    BrownMushroom,
    RedMushroom,
    SugarCane,
    GrassBlock,
    OakLeaves,
    BirchLeaves,
    SpruceLeaves,
    BirchWood,
    SpruceWood,
    TNT,
    Snow,
    Water,
    // 0.1.0 alpha
    OakStairs,
    CobblestoneStairs,
    CoalOre,
    IronOre,
    DiamondOre,
    RedstoneOre,
    LapisLazuliOre,
    Ice,
    Gravel,
    Clay,
    Lava,
    Farmland,
    OakDoor,
    IronDoor,
    WoodSlab,
    CobblestoneSlab,
    SandstoneSlab,
    InvisibleBedrock,
    // 0.1.3 alpha
    InfoUpdate,
    InfoUpdate2,
    Cactus,
    // 0.2.0 alpha
    Fence,
    FenceGate,
    // White Wool
    SnowBlock,
    BookShelf,
    LapisLazuliBlock,
    MossyCobblestone,
    Reserved6,
    StoneShovel,
    StonePickaxe,
    StoneAxe,
    StoneSword,
    Shears,
    Compass,
    Clock,
    Stick,
    Bowl,
    Paper,
    Book,
    Leather,
    Brick,
    ClayBall,
    Slimeball,
    Snowball,
    Sugar,
    Bone,
    Gunpowder,
    String,
    Feather,
    Arrow,
    GlowstoneDust,
    Wheat,
    IronIngot,
    GoldIngot,
    Diamond,
    WoodenPickaxe,
    WoodenShovel,
    WoodenAxe,
    WoodenSword,
    IronPickaxe,
    IronShovel,
    IronAxe,
    IronSword,
    GoldPickaxe,
    GoldShovel,
    GoldAxe,
    GoldSword,
    DiamondPickaxe,
    DiamondShovel,
    DiamondAxe,
    DiamondSword,
    // 0.3.0 alpha
    CraftingTable,
    BrickSlab,
    BrickStair,
    DandelionYellow,
    Coal,
    LapisLazuli,
    BoneMeal,
    CactusGreen,
    Charcoal,
    CocoaBeans,
    CyanDye,
    GrayDye,
    InkSac,
    LightBlueDye,
    LightGrayDye,
    LimeDye,
    MagentaDye,
    OrangeDye,
    PinkDye,
    PurpleDye,
    RoseRed,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Biomes {
    Plains,
    Desert,
    Forest,
    SnowyTundra,
    SnowyTaiga,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Entities {
    Player,
    Sheep,
    Pig,
    Zombie,
    Camera,
    Cow,
    Chicken,
}

const DEMO_BLOCKS: &[Blocks] = &[
    Blocks::Air,
    Blocks::Dirt,
    Blocks::Stone,
    Blocks::Cobblestone,
    Blocks::WoodPlanks,
    Blocks::Sand,
    Blocks::Sandstone,
    Blocks::Wool,
    Blocks::Glass,
    Blocks::BlockOfIron,
    Blocks::BlockOfGold,
    Blocks::BlockOfDiamond,
    Blocks::Obsidian,
    Blocks::Bricks,
    Blocks::OakWood,
    Blocks::StoneSlab,
    Blocks::Ladder,
    Blocks::Torch,
    Blocks::Dandelion,
    Blocks::Rose,
    Blocks::BrownMushroom,
    Blocks::RedMushroom,
    Blocks::SugarCane,
    Blocks::GrassBlock,
    Blocks::OakLeaves,
    Blocks::BirchLeaves,
    Blocks::SpruceLeaves,
    Blocks::BirchWood,
    Blocks::SpruceWood,
    Blocks::TNT,
    Blocks::Snow,
    Blocks::Water,
];

const DEMO_ITEMS: &[Items] = &[
    Items::Air,
    Items::Dirt,
    Items::Stone,
    Items::Cobblestone,
    Items::WoodPlanks,
    Items::Sand,
    Items::Sandstone,
    Items::Wool,
    Items::Glass,
    Items::BlockOfIron,
    Items::BlockOfGold,
    Items::BlockOfDiamond,
    Items::Obsidian,
    Items::Bricks,
    Items::OakWood,
    Items::StoneSlab,
    Items::Ladder,
    Items::Torch,
    Items::Dandelion,
    Items::Rose,
    Items::BrownMushroom,
    Items::RedMushroom,
    Items::SugarCane,
    Items::GrassBlock,
    Items::OakLeaves,
    Items::BirchLeaves,
    Items::SpruceLeaves,
    Items::BirchWood,
    Items::SpruceWood,
    Items::TNT,
    Items::Snow,
    Items::Water,
];

const DEMO_ENTITIES: &[Entities] = &[Entities::Player];

const V0_1_0_ADDED_BLOCKS: &[Blocks] = &[
    Blocks::OakStairs,
    Blocks::CobblestoneStairs,
    Blocks::CoalOre,
    Blocks::IronOre,
    Blocks::DiamondOre,
    Blocks::RedstoneOre,
    Blocks::LapisLazuliOre,
    Blocks::Ice,
    Blocks::Gravel,
    Blocks::Clay,
    Blocks::Lava,
    Blocks::Farmland,
    Blocks::OakDoor,
    Blocks::IronDoor,
    Blocks::WoodSlab,
    Blocks::CobblestoneSlab,
    Blocks::SandstoneSlab,
    Blocks::InvisibleBedrock,
];
const V0_1_0_ADDED_ITEMS: &[Items] = &[
    Items::OakStairs,
    Items::CobblestoneStairs,
    Items::CoalOre,
    Items::IronOre,
    Items::DiamondOre,
    Items::RedstoneOre,
    Items::LapisLazuliOre,
    Items::Ice,
    Items::Gravel,
    Items::Clay,
    Items::Lava,
    Items::Farmland,
    Items::OakDoor,
    Items::IronDoor,
    Items::WoodSlab,
    Items::CobblestoneSlab,
    Items::SandstoneSlab,
    Items::InvisibleBedrock,
];
const V0_1_0_ADDED_ENTITIES: &[Entities] = &[Entities::Camera];

const V0_1_0_BLOCKS: &[Blocks] = concat_slices!([Blocks]: DEMO_BLOCKS, V0_1_0_ADDED_BLOCKS);
const V0_1_0_ITEMS: &[Items] = concat_slices!([Items]: DEMO_ITEMS, V0_1_0_ADDED_ITEMS);
const V0_1_0_ENTITIES: &[Entities] =
    concat_slices!([Entities]: DEMO_ENTITIES, V0_1_0_ADDED_ENTITIES);
const V0_1_0_BIOMES: &[Biomes] = &[
    Biomes::Plains,
    Biomes::Desert,
    Biomes::Forest,
    Biomes::SnowyTundra,
    Biomes::SnowyTaiga,
];

const V0_1_3_ADDED_BLOCKS: &[Blocks] = &[Blocks::InfoUpdate, Blocks::InfoUpdate2, Blocks::Cactus];
const V0_1_3_ADDED_ITEMS: &[Items] = &[Items::InfoUpdate, Items::InfoUpdate2, Items::Cactus];
const V0_1_3_BLOCKS: &[Blocks] = concat_slices!([Blocks]: V0_1_0_BLOCKS, V0_1_3_ADDED_BLOCKS);
const V0_1_3_ITEMS: &[Items] = concat_slices!([Items]: V0_1_0_ITEMS, V0_1_3_ADDED_ITEMS);

const V0_2_0_ADDED_BLOCKS: &[Blocks] = &[
    Blocks::Fence,
    Blocks::FenceGate,
    // White Wool
    Blocks::SnowBlock,
    Blocks::BookShelf,
    Blocks::LapisLazuliBlock,
    Blocks::MossyCobblestone,
    Blocks::Reserved6,
];

const V0_2_0_ADDED_ITEMS: &[Items] = &[
    Items::Fence,
    Items::FenceGate,
    // White Wool
    Items::SnowBlock,
    Items::BookShelf,
    Items::LapisLazuliBlock,
    Items::MossyCobblestone,
    Items::Reserved6,
];

const V0_2_0_ADDED_ENTITIES: &[Entities] = &[Entities::Sheep, Entities::Pig, Entities::Zombie];
const V0_2_0_BLOCKS: &[Blocks] = concat_slices!([Blocks]: V0_1_3_BLOCKS, V0_2_0_ADDED_BLOCKS);
const V0_2_0_ENTITIES: &[Entities] =
    concat_slices!([Entities]: V0_1_0_ENTITIES, V0_2_0_ADDED_ENTITIES);

const V0_3_0_ADDED_BLOCKS: &[Blocks] =
    &[Blocks::CraftingTable, Blocks::BrickSlab, Blocks::BrickStair];

const V0_3_0_ADDED_ITEMS: &[Items] = &[
    Items::CraftingTable,
    Items::BrickSlab,
    Items::BrickStair,
    Items::DandelionYellow,
    Items::Coal,
    Items::LapisLazuli,
    Items::BoneMeal,
    Items::CactusGreen,
    Items::Charcoal,
    Items::CocoaBeans,
    Items::CyanDye,
    Items::GrayDye,
    Items::InkSac,
    Items::LightBlueDye,
    Items::LightGrayDye,
    Items::LimeDye,
    Items::MagentaDye,
    Items::OrangeDye,
    Items::PinkDye,
    Items::PurpleDye,
    Items::RoseRed,
];

const V0_3_0_ADDED_ENTITIES: &[Entities] = &[Entities::Cow, Entities::Chicken];
const V0_3_0_BLOCKS: &[Blocks] = concat_slices!([Blocks]: V0_2_0_BLOCKS, V0_3_0_ADDED_BLOCKS);
const V0_3_0_ENTITIES: &[Entities] =
    concat_slices!([Entities]: V0_2_0_ENTITIES, V0_3_0_ADDED_ENTITIES);
